### ISSUE TITLE
Problem with creating virtualMachines on Windows10

### ISSUE THREAD

**Issue by ghost** [linuxpolska/WEBSSOOpenSourceDay2017#1]
After send command vagrant up <machinename> everythink is ok to error:
: invalid optioninuxpolska.pl: /vagrant/provision/bootstrap-node-rhel.sh: line 3: set: -
==> cas.websso.linuxpolska.pl: set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

Machine is running but without applications.

**Comment by kardasa** [comment]
Please provide additional info:
Vagrant version?
VBox version?
Did you follow the guide and installed the required plugins?
Please provide more output I have no idea in which moment you recived this error.
Which machine at what build stage.
Provide some lines before that error

**Comment by ghost** [comment]
Virtualbox latest version 5.5.22
Vagrant 1.9.5

Pozdrawiam
Rafał

**Comment by kardasa** [comment]
Hej czy na pewno chciałeś publikować na githubie tak szczegółowe informacje na Swój temat - byłbym raczej dość ostrożny w tej kwestii, ale to nie moje dane.
Sprawdzaliśmy działanie dla zbliżonej konfiguracji i nie było problemu przynajmniej z postawieniem środowiska.
Wszystkie skrypty mają opcje set -x nie rozumiem dla czego jeden padł był u Ciebie.
Czy nie edytowałeś tej 3 linii? Masz tam nadal set -x.
To jest skrypt odpalany dla wszystkich maszyn a wywalił się tylko dla ostatniej to wskazuje, że nastąpiła w nim jakaś zmiana w trakcie budowy.
W razie czego daj ponownie pulla:
git pull origin master
A następnie zniszcz wszystko i postaw ponownie.
vagrant destroy
Potwierdź zniszczenie maszyn i postaw je od początku jak systemy są pobrane w tmp nie będą ściągane ponownie.
vagrant up

**Comment by kardasa** [comment]
BTW jutro będę wcześniej jak będzie problem tylko z 1 maszyną to znajdź mnie gdzieś w korytarzu a go rozwiążemy.

**Comment by kardasa** [comment]
Problem jest spowodowany domyślną konfiguracja klienta gita w Windowsach, przy domyślnej konfiguracji klient Git pod Windows podczas klonowania dokonuje konwersji "znaków końca linii" w plikach tekstowych. Co powoduje, że na Windowsie skrypty nie chcą działać na maszynach wirtualnych. Zmiana konfiguracji jest oczywiście możliwa ale postaram się zablokować takie działanie globalnie, aby było ok bez względu na  to jaka jest konfiguracja klienta. Aby upewnić się, że to działa muszę dostać w swoje ręce Windowsa na fizycznej maszynie aby to przetestować - najpóźniej we wtorek powinienem móc to sprawdzić i wgram wtedy poprawkę. Opiszę wtedy procedurę postępowania dla osób, które sklonowały repozytorium wcześniej.

**Comment by kardasa** [comment]
Poprawka rozwiązująca problem (blokująca zmiany w znakach końca linii) została przetestowana i wgrana do repozytorium - teraz powinno być ok jeśli tylko składniki się pobiorą.
